CREATE DATABASE esteticadb;
USE esteticadb;

CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	fullname VARCHAR(500) NOT NULL,
	username VARCHAR(100) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL,
	created_at DATETIME NOT NULL
);
SELECT * FROM users